productName = "gg"
version = "0.36.0"
identifier = "au.gulbanana.gg"

[build]
beforeDevCommand = "npm run dev"
devUrl = "http://localhost:6973"
beforeBuildCommand = "npm run build"
frontendDist = "dist"

[app]

[[app.windows]]
label = "main"
title = "GG - Gui for JJ"
decorations = true
resizable = true
focus = true
width = 1280
height = 720
visible = false
dragDropEnabled = false

[[app.security.capabilities]]
identifier = "main-capability"
description = "Capability for the main window"
windows = ["main"]
permissions = [
    "core:path:default",
    "core:event:default",
    "core:window:default",
    "core:app:default",
    "core:resources:default",
    "core:menu:default",
    "core:tray:default",
    "shell:allow-open",
]

[bundle]
active = true # Comment this out or set to false to disable bundle compilation
targets = "all"
icon = [
    "resources/icons/32x32.png",
    "resources/icons/128x128.png",
    "resources/icons/128x128@2x.png",
    "resources/icons/icon.icns",
    "resources/icons/icon.ico",
]

[bundle.windows]
signCommand = "trusted-signing-cli -e https://wus2.codesigning.azure.net/ -a agile-signing -c cloud-apps %1"

[plugins]
