productName = "gg"
version = "0.38.4"
identifier = "au.gulbanana.gg"

[[app.security.capabilities]]
identifier = "main-capability"
description = "Capability for all windows"
windows = ["repo-*"]
permissions = [
    "core:path:default",
    "core:event:default",
    "core:window:default",
    "core:app:default",
    "core:resources:default",
    "core:menu:default",
    "core:tray:default",
    "shell:allow-open",
]

[build]
beforeBuildCommand = "npm run build"
beforeDevCommand = "npx vite"
devUrl = "http://localhost:6973"
frontendDist = "dist"
features = ["app"]

[bundle]
active = true # Comment this out or set to false to disable bundle compilation
targets = "all"
icon = [
    "res/icons/32x32.png",
    "res/icons/128x128.png",
    "res/icons/128x128@2x.png",
    "res/icons/icon.icns",
    "res/icons/icon.ico",
]

[bundle.windows]
signCommand = "trusted-signing-cli -e https://wus2.codesigning.azure.net/ -a agile-signing -c cloud-apps %1"

[plugins]
