[gg]
default-mode = "gui" # "gui" or "web"

[gg.queries]
# Number of commits to load per call
log-page-size = 1000

# Some query settings will default to false instead of true if a repo has this many commits.
large-repo-heuristic = 100000

# Take a snapshot when the window gains focus; slow in large checkouts. 
# When disabled, snapshots will still be created if you run commands. 
# auto-snapshot = 

[gg.ui]
# Stores a list of recently opened directories for shell integration
recent-workspaces = []

# When unset, GG will not update recent-workspaces or system jump lists.
track-recent-workspaces = true

# When set, bookmarks that are local-only or remote-only will be visually indicated.
mark-unpushed-bookmarks = true

# "light" or "dark". If empty, your OS settings will be used.
theme-override = ""

[gg.web]
default-port = 0       # Port to bind to in web mode (0 = random)
client-timeout = "10m" # Disconnect clients after this duration of inactivity
launch-browser = true  # Open browser automatically when starting web mode

[gg.presets]
# add values here to customise the presets in the log pane. "kebab-case" keys will become "Title Case" entries. examples:
# local-bookmarks = "bookmarks() & ~remote_bookmarks()"
# WC-ancestors = "..@"
